config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'tweets#index'
  get :about, to: 'pages#about'

  resources :tweets
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tweets
#
#  id         :bigint           not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tweets_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Tweet < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 280 }

  # after_create_commit -> { broadcast_prepend_later_to "tweets" }
  # after_update_commit -> { broadcast_replace_later_to "tweets" }
  # after_destroy_commit -> { broadcast_remove_to "tweets" }
  broadcasts_to ->(_tweet) { 'tweets' }, inserts_by: :prepend

  scope :ordered, -> { order(created_at: :desc) }
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about; end
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_user_tweet, only: %i[edit update destroy]

  def index
    @tweets = Tweet.all.includes(:user).ordered
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.build(tweet_params.merge(user: current_user))
    if @tweet.save
      respond_to do |format|
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Tweet was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @tweet.update(tweet_params)
      respond_to do |format|
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'Tweet was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_path, notice: 'Tweet was successfully destroyed.' }
      format.turbo_stream { flash.now[:notice] = 'Tweet was successfully destroyed.' }
    end
  end

  private

  def set_user_tweet
    @tweet = current_user.tweets.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash-message', partial: 'layouts/flash_message'
  end
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/views/layouts/_dark_mode_switcher.html.slim
.flex.justify-center.items-center
  button#theme-toggle.rounded-full.hover:bg-gray-100.dark:hover:bg-gray-700.bg-gray-200.dark:bg-gray-600.w-11.h-11.flex.items-center.justify-center
    svg#theme-toggle-dark-icon.fill-blue-500.block.dark:hidden.w-6.h-6 fill="currentColor" viewBox="0 0 20 20"
      path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"
    svg#theme-toggle-light-icon.fill-yellow-500.hidden.dark:block.w-6.h-6 fill="currentColor" viewBox="0 0 20 20"
      path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"

app/views/layouts/_dark_mode_switcher_script.html.erb
<script>
    if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
        document.documentElement.classList.add('dark');
    } else {
        document.documentElement.classList.remove('dark')
    }
</script>

app/views/layouts/_flash_message.html.erb
<% if flash.any? %>
  <div data-controller='flash-message' id='flash-message' class="fixed right-0 z-40 top-16">
    <div class='shadow-md transition-transform transform animate-fade-in'>
      <% flash.each do |type, message| %>
        <%= render FlashMessage::Component.new(type: type, message: message) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.slim
footer.relative.z-50.w-full.py-4.bg-white.border-t.border-gray-200.dark:bg-gray-800.dark:border-gray-700
  .container.mx-auto.text-center
    = link_to 'About', about_path, class: 'text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 font-medium'
    p.text-sm.dark:text-white © #{Time.now.year} Babbler. All rights reserved.

app/views/layouts/_header.html.slim
nav.fixed.top-0.z-50.w-full.h-16.bg-white.border-b.border-gray-200.dark:bg-gray-800.dark:border-gray-700
  .h-full.px-3.lg:px-5
    .flex.items-center.justify-between.h-full
      .flex.items-center.justify-start.rtl:justify-end.h-full
        - if current_user
          button.inline-flex.items-center.p-2.text-sm.text-gray-500.rounded-bl-lg.rounded-br-lg.sm:hidden.hover:bg-gray-100.focus:outline-none.focus:ring-2.focus:ring-gray-200.dark:text-gray-400.dark:hover:bg-gray-700.dark:focus:ring-gray-600[
            data-drawer-target="logo-sidebar"
            data-drawer-toggle="logo-sidebar"
            aria-controls="logo-sidebar"
            type="button"
          ]
            span.sr-only Open sidebar
            = heroicon "bars-3", options: { class: "w-6 h-6" }

        = link_to root_path, class: 'flex items-center md:me-24 h-full' do
          picture
            source srcset=asset_path('logo.webp') type="image/webp"
            = image_tag 'logo.webp', alt: 'Babbler Logo', class: 'h-11 me-3 w-full object-cover'
          span.self-center.text-xl.font-semibold.sm:text-2xl.whitespace-nowrap.dark:text-white Babbler

      .flex.items-center.ms-3.h-full.gap-2
        = render 'layouts/dark_mode_switcher'
        
        .relative.h-full.flex.items-center
          button#user-menu-button.flex.items-center.justify-center.w-11.h-11.rounded-full.bg-gray-200.dark:bg-gray-600.hover:bg-gray-100.dark:hover:bg-gray-700[
            type="button"
            aria-expanded="false"
            data-dropdown-toggle="dropdown-user"
          ]
            span.sr-only Menu
            - if current_user
              = render Avatar::Component.new(user: current_user)
            - else
              = heroicon 'user', options: { class: 'w-6 h-6 text-black dark:text-white' }

          #dropdown-user.z-50.hidden.text-base.list-none.bg-white.divide-y.divide-gray-100.rounded-bl-lg.rounded-br-lg.shadow.dark:bg-gray-700.dark:divide-gray-600[
            class="min-w-[200px]"
            style="margin: 0; transform: translate3d(0, 0, 0) !important;"
            data-popper-placement="bottom"
          ]
            - if current_user
              .px-4.py-3
                p.text-sm.text-gray-900.dark:text-white = current_user.username
                p.text-sm.font-medium.text-gray-900.truncate.dark:text-gray-300 = current_user.email
              ul.py-1
                li = link_to 'Profile', '#', class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white whitespace-nowrap"
                li = link_to 'Sign Out', destroy_user_session_path, 
                    data: { "turbo-method": :delete }, 
                    class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white whitespace-nowrap"
            - else
              ul.py-1
                li = link_to 'Sign in', new_user_session_path, 
                    class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white whitespace-nowrap"


app/views/layouts/_sidebar.html.erb
<aside id="logo-sidebar" class="fixed top-0 left-0 w-48 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-gray-200 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700" aria-label="Sidebar">
   <div class="h-full px-3 pb-4 overflow-y-auto bg-white dark:bg-gray-800">
      <ul class="space-y-2 font-medium">
         <li>
            <%= link_to root_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do  %>
               <%= heroicon 'home', options: { class: 'flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white' } %>
               <span class="flex-1 ms-3 whitespace-nowrap">Home</span>
            <% end %>
         </li>
         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <%= heroicon 'star', options: { class: 'flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white' } %>
               <span class="flex-1 ms-3 whitespace-nowrap">Profile</span>
            </a>
         </li>
         <li>
            <%= link_to destroy_user_session_path, data: { "turbo-method": :delete }, class: 'flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group' do %>
               <%= heroicon 'arrow-right', options: { class: 'flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white' } %>
               <span class="flex-1 ms-3 whitespace-nowrap">Sign Out</span>
            <% end %>
         </li>
      </ul>
   </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babbler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= render 'layouts/dark_mode_switcher_script' %>
  </head>

  <body class="min-h-screen">
    <%= render 'layouts/header' %>

    <%= turbo_frame_tag 'flash-message' do %>
      <%= render 'layouts/flash_message' %>
    <% end %>

    <%- if current_user %>
      <%= render 'layouts/sidebar' %>
      <main class="p-4 sm:ml-48 mt-14">
        <div class="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700">
          <%= yield %>
        </div>
      </main>
    <% else %>
      <main class="p-4 mt-14">
        <div class="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700">
          <%= yield %>
        </div>
      </main>
    <% end %>

    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.turbo.min.js"></script>
  </body>
</html>

app/views/pages/about.html.slim
section#about.min-h-screen.py-16
  .container.mx-auto
    .flex.flex-col.items-center.lg:items-start.gap-8
      .flex.flex-col.items-center.lg:flex-row.lg:items-start.gap-8
        = image_tag "about.jpg", class: "place-self-center inset-0 w-48 h-48 object-cover rounded-full shadow-lg hover:shadow-xl transition-shadow duration-300", alt: "Profile picture"
        .text-center.lg:text-left
          h1.text-4xl.font-bold.mb-4 Vitalii Kasianchuk
          p.text-xl.text-gray-600.mb-6 Full Stack Ruby on Rails Developer
          p.text-gray-600.max-w-2xl.leading-relaxed
            | I am a Full Stack Ruby on Rails Developer with over 5 years of experience in web development. 
            | I have successfully delivered several interviews and collaborated effectively with colleagues. 
            | My recent project, lasting over 3 years, involved extensive full-stack development, including 
            | developing new features and API integrations. I am passionate about delivering robust and 
            | scalable solutions and continuously strive to expand my knowledge and expertise in the 
            | software development field.

      .w-full
        h2#skills.text-2xl.font-bold.text-gray-800.mb-8.text-center.lg:text-left
          a.hover:text-blue-600.transition-colors href="#skills" Skills

        .space-y-8
          .space-y-2
            .text-sm.font-medium.text-gray-500.mb-3 Expert Level
            .flex.flex-wrap.gap-3.[content:flex-start]
              - expert_skills = ['Ruby on Rails', 'PostgreSQL', 'Ruby', 'Redis', 'Rspec', 'HTML', 'CSS', 'Teamwork']
              - expert_skills.each do |skill|
                div class="px-4 py-2 rounded-full bg-blue-500 text-white font-medium text-center whitespace-nowrap [order:#{skill.length}]" = skill

          .space-y-2
            .text-sm.font-medium.text-gray-500.mb-3 Advanced Level
            .flex.flex-wrap.gap-3.[content:flex-start]
              - advanced_skills = ['JavaScript', 'React', 'Stimulus', 'AWS', 'MySQL', 'MongoDB', 'Sidekiq', 'CI/CD', 'Mentoring']
              - advanced_skills.each do |skill|
                div class="px-4 py-2 rounded-full bg-yellow-500 text-white font-medium text-center whitespace-nowrap [order:#{skill.length}]" = skill

          .space-y-2
            .text-sm.font-medium.text-gray-500.mb-3 Intermediate Level
            .flex.flex-wrap.gap-3.[content:flex-start]
              - intermediate_skills = ['Effective Communication', 'Result-orientation', 'Critical Thinking', 'Bootstrap', 'Tailwind', 'GraphQL', 'BuildKite', 'Postman', 'OpenAPI', 'Datadog', 'Splunk', 'Honeybadger', 'Opsgenie', 'Jira', 'Figma', 'Terraform', 'Go']
              - intermediate_skills.each do |skill|
                div class="px-4 py-2 rounded-full bg-yellow-200 text-yellow-800 font-medium text-center whitespace-nowrap [order:#{skill.length}]" = skill

    .w-full.py-4
      h2#experience.text-2xl.font-bold.text-gray-800.mt-8.text-center.lg:text-left
        a.hover:text-blue-600.transition-colors href="#experience" Experience

      .space-y-12
        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              = link_to "IFNTUNG", "https://nung.edu.ua/", class: "text-blue-600 hover:text-blue-800 font-bold text-lg", target: "_blank", rel: "noopener"
              h3.text-lg.font-medium Assistant at the Department of Software Engineering
            time.text-gray-500.whitespace-nowrap 2024 - NOW
          ul.list-disc.list-inside.space-y-2.text-gray-600
            li Teaching programming fundamentals to first-year students
            li Developing and maintaining educational materials
            li Conducting practical classes and workshops

        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              = link_to "EPAM", "https://www.epam.com/", class: "text-blue-600 hover:text-blue-800 font-bold text-lg", target: "_blank", rel: "noopener"
              h3.text-lg.font-medium Software Developer
            time.text-gray-500.whitespace-nowrap 2021 - 2024
          ul.list-disc.list-inside.space-y-2.text-gray-600
            li Full stack developer in the international team
            li Responsible for implementing new features, supporting, improving, and refactoring existing functionality
            li Contacted the business side to ensure the best implementation of their needs based on requirements
            li
              | Worked with technologies: 
              span.text-gray-700.font-medium AWS, React, Stripe, DataDog, Honeybadger, and GitHub Copilot
            li The project was based on the sprints system, and every day, we had calls with a customer
            li Conducted interviews and participated in the mentor program

        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              h3.text-blue-600.hover:text-blue-800.font-bold.text-lg Webmil
              h3.text-lg.font-medium Software Developer
            time.text-gray-500.whitespace-nowrap 2020 - 2021
          ul.list-disc.list-inside.space-y-2.text-gray-600
            li Full stack single developer in a foreign project
            li Developed and implemented new features on the API side for mobile and web applications
            li Implemented Stripe payments
            li Provided long-term support

        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              h3.text-blue-600.hover:text-blue-800.font-bold.text-lg Webmil
              h3.text-lg.font-medium Software Developer
            time.text-gray-500.whitespace-nowrap 2019 - 2020
          ul.list-disc.list-inside.space-y-2.text-gray-600
            li Full stack developer in a domestic project
            li Developed and implemented a new customer portal and admin panel
            li Added new features related to QR codes, their generation, and scanning
            li
              | Worked with technologies: 
              span.text-gray-700.font-medium Ruby, Redis, PostgreSQL, OpenAPI Specification (OAS), and MySQL
            li Provided long-term support

        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              h3.text-blue-600.hover:text-blue-800.font-bold.text-lg Webmil
              h3.text-lg.font-medium Software Developer
            time.text-gray-500.whitespace-nowrap 2018 - 2019
          ul.list-disc.list-inside.space-y-2.text-gray-600
            li Full stack developer in a foreign project
            li E-commerce website for an EU distribution company
            li Participated in the development of the project from scratch
            li Migrated logic from the service to a separate gem
            li
              | Used technologies: 
              span.text-gray-700.font-medium Ruby, Ruby on Rails, MongoDB, Rails Admin, Redis

        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              h3.text-blue-600.hover:text-blue-800.font-bold.text-lg Webmil
              h3.text-lg.font-medium Software Developer
            time.text-gray-500.whitespace-nowrap 2018
          ul.list-disc.list-inside.space-y-2.text-gray-600
            li Full stack developer
            li Recruitment platform for optimized selection of candidates for the employer
            li Created an automated system for collecting and sorting information that can interact with it
            li Helped this platform optimize the recruitment processes
            li Participated in the development of the project from scratch
            li
              | Used technologies: 
              span.text-gray-700.font-medium Ruby, Ruby on Rails, MongoDB, Stimulus

    .w-full
      h2#education.text-2xl.font-bold.text-gray-800.my-8.text-center.lg:text-left
        a.hover:text-blue-600.transition-colors href="#education" Education

      .space-y-12
        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              h3.text-blue-600.hover:text-blue-800.font-bold.text-lg Self Education
              .text-lg.font-medium Continuous Learning
            time.text-gray-500.whitespace-nowrap 2018 - NOW
          .space-y-2.text-gray-600
            p EPAM, LinkedIn, Youtube
            p Constantly improving skills through online platforms and professional resources

        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              = link_to "IFNTUNG", "https://nung.edu.ua/", class: "text-blue-600 hover:text-blue-800 font-bold text-lg", target: "_blank", rel: "noopener"
              h3.text-lg.font-medium Software Engineer
            time.text-gray-500.whitespace-nowrap 2023 - 2024
          p.text-gray-600.italic Ivano-Frankivsk National Technical University of Oil and Gas

        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              h3.text-blue-600.hover:text-blue-800.font-bold.text-lg Professional Courses
              .text-lg.font-medium Ruby on Rails Development
            time.text-gray-500.whitespace-nowrap 2018
          .space-y-2.text-gray-600
            p.italic Ivano-Frankivsk SoftServe, Webmil
            p Intensive training in web development using Ruby on Rails framework

        article.space-y-4
          header.flex.flex-col.lg:flex-row.lg:items-center.lg:justify-between.gap-2
            div
              = link_to "IFNMU", "https://www.ifnmu.edu.ua/en/", class: "text-blue-600 hover:text-blue-800 font-bold text-lg", target: "_blank", rel: "noopener"
              h3.text-lg.font-medium Master of Pediatrician
            time.text-gray-500.whitespace-nowrap 2010 - 2018
          p.text-gray-600.italic Ivano-Frankivsk National Medical University

app/views/tweets/_form.html.slim
= form_with(model: tweet, html: { class: "bg-white shadow-md rounded-lg p-4 mb-4 relative" }) do |f|
  div data-controller="textarea-autogrow" data-textarea-autogrow-max-length-value="280"    
    .flex.items-start.space-x-3
      .flex-shrink-0.hidden.lg:block
        = render Avatar::Component.new(user: current_user)

      .flex-grow.relative
        .mb-4.lg:mb-0
          .lg:absolute.right-0.lg:-top-6.flex.flex-col.lg:flex-row.items-start.lg:items-center.justify-between.w-full.mb-2.lg:mb-0
            .text-red-600.text-sm.mb-2.lg:mb-0.order-first data-textarea-autogrow-target="error"
              = tweet.errors.full_messages.to_sentence.capitalize if tweet.errors.any?
            span.text-sm.whitespace-nowrap.order-last data-textarea-autogrow-target="counter"
              span.font-medium data-textarea-autogrow-target="counterNumber" 280
              |  characters remaining

        = f.text_area :content,
          placeholder: "What do you want to say...", 
          class: "w-full p-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none mb-8",
          rows: 2,
          data: { textarea_autogrow_target: "textarea" }

    .flex.space-x-2.absolute.bottom-4.right-4
      button type="submit" class="text-gray-400 hover:text-blue-600"
        = heroicon 'paper-airplane', options: { class: 'w-5 h-5' }
      
      = link_to tweets_path, class: "text-gray-400 hover:text-yellow-600" do
        = heroicon 'x-mark', options: { class: 'w-5 h-5' }

app/views/tweets/_tweet.html.slim
= turbo_frame_tag tweet do
  .bg-white.shadow-md.rounded-lg.p-4.mb-4.relative
    .flex.items-start.space-x-3
      .flex-shrink-0
        = render Avatar::Component.new(user: tweet.user)

      .flex.flex-col.flex-grow.pb-6
        .flex.items-center.space-x-2
          span.font-medium.text-gray-900= tweet.user.username
          span.text-sm.text-gray-500= time_ago_in_words(tweet.created_at)
        
        p.text-gray-800.mt-1.break-words= tweet.content

    - if current_user && tweet.user == current_user
      .flex.space-x-2.absolute.bottom-4.right-4
        = link_to edit_tweet_path(tweet), class: 'text-gray-400 hover:text-yellow-600' do
          = heroicon 'pencil', options: { class: 'w-5 h-5' }
        
        = button_to tweet_path(tweet), method: :delete, data: { confirm: 'Are you sure?', "turbo-method": :delete, turbo_frame: "_top" }, class: 'text-gray-400 hover:text-red-600' do
          = heroicon 'trash', options: { class: 'w-5 h-5' }

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend "tweets", @tweet %>
<%= turbo_stream.update 'new_tweet', "" %>
<%= render_turbo_stream_flash_messages %>

app/views/tweets/destroy.turbo_stream.erb
<%= turbo_stream.remove @tweet %>
<%= render_turbo_stream_flash_messages %>

app/views/tweets/edit.html.slim
= turbo_frame_tag @tweet do
  = render 'tweets/form', tweet: @tweet

app/views/tweets/index.html.slim
= turbo_stream_from "tweets"

- if current_user
  = link_to 'New Tweet', new_tweet_path, data: { turbo_frame: 'new_tweet' }, class: 'px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 inline-block mb-4'
  = turbo_frame_tag 'new_tweet'

= turbo_frame_tag 'tweets' do
  = render @tweets

app/views/tweets/new.html.slim
= turbo_frame_tag @tweet do
  = render 'tweets/form', tweet: @tweet

app/views/tweets/show.html.slim
= render @tweet

app/views/tweets/update.turbo_stream.erb
<%= turbo_stream.replace @tweet %>
<%= render_turbo_stream_flash_messages %>